name: 发布

on:
  workflow_dispatch:
env:
  JAVA_21_RULE: ">=fabric-1.20.5,>=neoforge-1.20.2"
  JAVA_17_RULE: ">=fabric-1.16.5,>=forge-1.17"
  JAVA_8_RULE: "=forge-1.16.5"
permissions:
  contents: write
jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Generate Matrix
        id: set-matrix
        run: |
          chmod 777 matrix.sh && ./matrix.sh -path "fabric,forge,neoforge"

  build:
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Get JDK Version
        run: chmod 777 jdk_rules.sh && ./jdk_rules.sh "${{ matrix.config.mc-loader }}" "${{ matrix.config.mc-version }}" "${{ env.JAVA_21_RULE }}" "${{ env.JAVA_17_RULE }}" "${{ env.JAVA_8_RULE }}"

      - name: Chose JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Read version.txt and save to variable
        run: |
          mod_version=$(cat version.txt)
          echo "Version: $mod_version"
          echo "MOD_VERSION=$mod_version" >> "$GITHUB_ENV"
      - name: Init Files
        run: |
          chmod 777 init.sh && ./init.sh
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ matrix.config.mc-version }}+${{ matrix.config.mc-loader }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ matrix.config.mc-version }}+${{ matrix.config.mc-loader }}-gradle-
      - name: Build
        run: |
          cd ${{ matrix.config.mc-loader }}/${{ matrix.config.mc-loader }}-${{ matrix.config.mc-version }}
          chmod 777 gradlew
          ./gradlew publish
          ./gradlew build
          cd ../..
        env:
          KITUIN_USERNAME: ${{ secrets.KITUIN_USERNAME }}
          KITUIN_PASSWORD: ${{ secrets.KITUIN_PASSWORD }}
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: zhVN1dvW
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 818089
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          name: ChatImage-${{ env.MOD_VERSION }}+${{ matrix.config.mc-version }}+${{ matrix.config.mc-loader }}.jar
          version: ${{ env.MOD_VERSION }}+${{ matrix.config.mc-version }}+${{ matrix.config.mc-loader }}
          version-type: beta
          loaders: ${{ matrix.config.publish-loaders }}
          game-versions: ${{ matrix.config.publish-version }}
          game-version-filter: releases
          files: ChatImage-jar/${{ env.MOD_VERSION }}/*.jar
